# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import robot_data_pb2 as robot__data__pb2


class RobotStub(object):
    """python3 -m grpc_tools.protoc --python_out=./ --grpc_python_out=./ -I. robot_data.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCarData = channel.unary_unary(
                '/robot.Robot/GetCarData',
                request_serializer=robot__data__pb2.Empty.SerializeToString,
                response_deserializer=robot__data__pb2.CarData.FromString,
                )
        self.GetYoloResult = channel.unary_unary(
                '/robot.Robot/GetYoloResult',
                request_serializer=robot__data__pb2.Empty.SerializeToString,
                response_deserializer=robot__data__pb2.YoloResult.FromString,
                )
        self.GetFaceResult = channel.unary_unary(
                '/robot.Robot/GetFaceResult',
                request_serializer=robot__data__pb2.Empty.SerializeToString,
                response_deserializer=robot__data__pb2.FaceResult.FromString,
                )
        self.GetYoloActionResult = channel.unary_unary(
                '/robot.Robot/GetYoloActionResult',
                request_serializer=robot__data__pb2.Empty.SerializeToString,
                response_deserializer=robot__data__pb2.YoloActionResult.FromString,
                )
        self.SetTwistKeyboard = channel.unary_unary(
                '/robot.Robot/SetTwistKeyboard',
                request_serializer=robot__data__pb2.Keyboard.SerializeToString,
                response_deserializer=robot__data__pb2.CarMessage.FromString,
                )
        self.GetHeadCamImage = channel.unary_stream(
                '/robot.Robot/GetHeadCamImage',
                request_serializer=robot__data__pb2.Empty.SerializeToString,
                response_deserializer=robot__data__pb2.ImageData.FromString,
                )


class RobotServicer(object):
    """python3 -m grpc_tools.protoc --python_out=./ --grpc_python_out=./ -I. robot_data.proto

    """

    def GetCarData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetYoloResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFaceResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetYoloActionResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTwistKeyboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHeadCamImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCarData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarData,
                    request_deserializer=robot__data__pb2.Empty.FromString,
                    response_serializer=robot__data__pb2.CarData.SerializeToString,
            ),
            'GetYoloResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetYoloResult,
                    request_deserializer=robot__data__pb2.Empty.FromString,
                    response_serializer=robot__data__pb2.YoloResult.SerializeToString,
            ),
            'GetFaceResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFaceResult,
                    request_deserializer=robot__data__pb2.Empty.FromString,
                    response_serializer=robot__data__pb2.FaceResult.SerializeToString,
            ),
            'GetYoloActionResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetYoloActionResult,
                    request_deserializer=robot__data__pb2.Empty.FromString,
                    response_serializer=robot__data__pb2.YoloActionResult.SerializeToString,
            ),
            'SetTwistKeyboard': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTwistKeyboard,
                    request_deserializer=robot__data__pb2.Keyboard.FromString,
                    response_serializer=robot__data__pb2.CarMessage.SerializeToString,
            ),
            'GetHeadCamImage': grpc.unary_stream_rpc_method_handler(
                    servicer.GetHeadCamImage,
                    request_deserializer=robot__data__pb2.Empty.FromString,
                    response_serializer=robot__data__pb2.ImageData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.Robot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Robot(object):
    """python3 -m grpc_tools.protoc --python_out=./ --grpc_python_out=./ -I. robot_data.proto

    """

    @staticmethod
    def GetCarData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.Robot/GetCarData',
            robot__data__pb2.Empty.SerializeToString,
            robot__data__pb2.CarData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetYoloResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.Robot/GetYoloResult',
            robot__data__pb2.Empty.SerializeToString,
            robot__data__pb2.YoloResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFaceResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.Robot/GetFaceResult',
            robot__data__pb2.Empty.SerializeToString,
            robot__data__pb2.FaceResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetYoloActionResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.Robot/GetYoloActionResult',
            robot__data__pb2.Empty.SerializeToString,
            robot__data__pb2.YoloActionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTwistKeyboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.Robot/SetTwistKeyboard',
            robot__data__pb2.Keyboard.SerializeToString,
            robot__data__pb2.CarMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHeadCamImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/robot.Robot/GetHeadCamImage',
            robot__data__pb2.Empty.SerializeToString,
            robot__data__pb2.ImageData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
